version: '3.3'

services:
    mysql:
        image: mysql:5.7
        ports:
            - ${DOCKER_MYSQL_PORT:-3306}:3306
        volumes:
            - ./var/data/mysql:/var/lib/mysql:cached
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
